# Site settings
title: Chris Gallagher
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Chris Gallagher portfolio.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cgallagher.adriandiaz.ca" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
analytics: UA-68230122-1

# Build settings
markdown: kramdown

collections:
  photography:
    output: true
    permalink: /photography/:title
  film:
    output: true
    permalink: /film/:title
  video:
    output: true
    permalink: /video/:title